### PR TITLE
Add dual-clock generator

### PR DESCRIPTION
**Pull request by stmach**

### CODE REVIEW

**Comment by stmach** [comment]
Added dual-clock generator for verification of dual-port SRAM models

**Comment by andreaskurth** [comment]
Thanks @stmach!

This is essentially the same as instantiating two `clk_rst_gen` with different periods and leaving the `rst_no` of one unconnected, right? So the primary benefit is convenience?

**Comment by stmach** [comment]
Sure. Actually just wrapping two instances of `clk_rst_gen` into this one would have been nicer, so no worries if you want to close this PR without merging 😅

**Comment by andreaskurth** [comment]
> Sure. Actually just wrapping two instances of `clk_rst_gen` into this one would have been nicer, so no worries if you want to close this PR without merging :sweat_smile:

:wink:  Your choice:  If you think `dual_clk_rst_gen` is worth having for convenience, please implement it by instantiating two `clk_rst_gen` inside (and don't forget to update `Bender.yml`).  Otherwise, please close this PR.

**Pull request closed without merging**
